version: '3'

services:
  app:
    image: openjdk:17-jre-slim
    container_name: java_app
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["java", "-jar", "app.jar"]
    depends_on:
      - db
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/my_database
      QUARKUS_DATASOURCE_USERNAME: my_user
      QUARKUS_DATASOURCE_PASSWORD: my_password
    ports:
      - "8080:8080"
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
